### PR TITLE
feat: add QC summary

### PR DESCRIPTION
**Pull request by a-frantz**

### CODE REVIEW

**Review by adthrasher — CHANGES_REQUESTED** [review]
Please add a meta section to the `qc_summary` task. I think that will help any external users understand why/what we are cherry-picking from the multiqc report.

**Comment by a-frantz** [comment]
> Please add a meta section to the `qc_summary` task. I think that will help any external users understand why/what we are cherry-picking from the multiqc report.

Is my latest commit what you had in mind? I wanted to avoid mentioning how we use it internally (i.e. "we parse these results and store them in a database." I think that would be the only comment of its sort in the repository)

**Comment by adthrasher** [comment]
It is. I might add that we are pulling stats from qualimap and ngsderive currently,  just for completeness.

**Review by adthrasher — APPROVED** [review]

**Comment by a-frantz** [comment]
@rahul0620

**Pull request merged**
