### PR TITLE
Qc refactor

### PR DESCRIPTION
**Pull request by a-frantz**

### CODE REVIEW

**Comment by a-frantz** [comment]
Are you guys ok renaming the 'strand' variables to `strandedness`? IMO it's more readable/explicit.

Also how well tested were all our Bash `if` tests that use in-line WDL parsing? `miniwdl check` has trouble with them, so I updated the samtools `nproc` tests to something it could parse.

But looking over the full project miniwdl check there are quit a few more. Not sure if it those are false errors on miniwdl's part, or if we messed up the in-line WDL var evaluations... They seem ok according to the spec, but I think miniwdl is pretty thorough and we've found undocumented WDL parsing quirks before.

**Review by adthrasher — APPROVED** [review]

**Comment by adthrasher** [comment]
I'm fine with renaming `strand` -> `strandedness` that is more explicit. I tested the `nproc` statements originally and it worked, but moving the parsing of WDL out of the task makes sense.

**Review by jsunny23 — APPROVED** [review]

**Comment by jsunny23** [comment]
I don't really mind either `strand` or `strandedness`, so if one's clearer, I think it's fine to update.

**Comment by claymcleod** [comment]
All sounds good to me.

**Pull request merged**
